weights: yolov5x6.pt
cfg: ''
data: /opt/ml/detection/yolov5/data/trash.yaml
hyp: data/hyps/hyp.scratch-p6.yaml
epochs: 75
batch_size: 6
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: true
single_cls: false
adam: false
sync_bn: false
workers: 8
entity: null
project: runs/train
name: yolo5x6_ms
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
patience: 15
save_dir: runs/train/yolo5x6_ms
